### ISSUE TITLE
awk error when annotating text with newlines

### ISSUE THREAD

**Issue by LLCampos** [lasigeBioTM/MER#37]
Running this command:

```shell
bash get_entities.sh "oxygen carbon" ChEBI
```

Returns:

```tsv
0	6	oxygen
7	13	carbon
```

The command

```shell
bash get_entities.sh "oxygen
carbon" ChEBI
```

Should return the same but instead it returns the following:

```
awk: cmd. line:1: BEGIN {IGNORECASE = 1} {sub(/carbon|oxygen/,"@@@@@@
awk: cmd. line:1:                                             ^ unterminated string
awk: cmd. line:1: BEGIN {IGNORECASE = 1} {sub(/carbon|oxygen/,"@@@@@@
awk: cmd. line:1:                                          ^ syntax error
```

This is relevant because there are cases in which you want to annotate text with multiple paragraphs. @fjmc any ideias why awk is raising this error?

**Comment by LLCampos** [comment]
The fix causes some problems to reappear:
https://github.com/lasigeBioTM/MER/issues/12
https://github.com/lasigeBioTM/MER/issues/24

And it really does not solve the bug. For example, if you run

```
bash get_entities.sh "oxygen

carbon" ChEBI
```

You get the same result as if the extra newline wasn't there. 

I think the problem is that the solution is replacing any number of contiguous newlines into just one white space? For some reason I can't test the "tr" tool on my terminal. 

_________________________________________________________

Wouldn't be better I we pushed bugfixes to the dev branch and only then to the master branch, when we are sure everything is working?

**Comment by fjmc** [comment]
```
echo "${a,,}"
-bash: ${a,,}: bad substitution
```
replaced by tr '[:upper:]' '[:lower:]'

**Comment by fjmc** [comment]
using IFS=$(echo -en ""); seems to have solve the problem
